eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.118:8761/eureka/

server:
  port: 8764

spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
